before:
  hooks:
    - go mod tidy
env:
  - CGO_ENABLED=0
builds:
  - mod_timestamp: '{{ .CommitTimestamp }}'
    goos:
      - linux
    goarch:
      - amd64
    binary: test
archives:
  - format: zip
    name_template: '{{ .Version }}_{{ .Os }}_{{ .Arch }}'
release:
  draft: true
  replace_existing_draft: true
